name: Validate YAML Syntax

on:
  push:
    # This wildcard '**' matches every branch and every path
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint.yml
          strict: true